name: Terraform New Relic Deployment
 
on:
  workflow_dispatch:
    inputs: 
      region :
        description: "Enter your region : "
        required: true  
        type: string   
  
env:
 BUCKET: mybucket-anu
 TFSTATE_FILE: anu.tfstate
 aws_region: ${{ github.event.inputs.region }}
 
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
      NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.aws_region }}
   
      - name: Terraform Init
        run: |
           terraform init -reconfigure -backend-config="bucket=${{ env.BUCKET }}" -backend-config="key=${{ env.TFSTATE_FILE }}" -backend-config="region=${{ env.aws_region }}" 
 
      - name: Terraform Plan
        run: |
           terraform plan -var='NEW_RELIC_API_KEY=${{ secrets.NEW_RELIC_API_KEY }}' -var='NEW_RELIC_ACCOUNT_ID=${{ secrets.NEW_RELIC_ACCOUNT_ID }}'
 
      - name: Terraform Apply 
        run: |
            terraform apply -auto-approve -var="NEW_RELIC_API_KEY=${{ secrets.NEW_RELIC_API_KEY }}" -var="NEW_RELIC_ACCOUNT_ID=${{ secrets.NEW_RELIC_ACCOUNT_ID }}" -input=false












# name: Terraform New Relic Deployment
 
# on:
#   workflow_dispatch:
  
# jobs:
#   terraform:
#     runs-on: ubuntu-latest
#     env:
#       NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
#       NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}

 
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
 
#       - name: Setup Terraform
#         uses: hashicorp/setup-terraform@v1
   
 
#       - name: Terraform Init
#         run: terraform init
 
#       - name: Terraform Plan
#         run: |
#           #terraform plan -input=false 
#            terraform plan -var='NEW_RELIC_API_KEY=${{ secrets.NEW_RELIC_API_KEY }}' -var='NEW_RELIC_ACCOUNT_ID=${{ secrets.NEW_RELIC_ACCOUNT_ID }}'
 
 
#       - name: Terraform Apply 
#         run: |
#           # terraform apply -auto-approve -input=false
#            # terraform apply -auto-approve -variable.tf=terraform.tfvars
#             terraform apply -auto-approve -var="NEW_RELIC_API_KEY=${{ secrets.NEW_RELIC_API_KEY }}" -var="NEW_RELIC_ACCOUNT_ID=${{ secrets.NEW_RELIC_ACCOUNT_ID }}"

