name: Terraform New Relic Deployment
 
on:
  workflow_dispatch:
  
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
      NEW_RELIC_ACCOUNT_ID: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
   
      - name: Terraform Init
        run: terraform init
 
      - name: Terraform Plan
        run: |
            terraform plan -var=${{env.NEW_RELIC_API_KEY}} -var=${{env.NEW_RELIC_ACCOUNT_ID}}
 
      - name: Terraform Apply 
        run: |
            terraform apply -var=${{env.NEW_RELIC_API_KEY}} -var=${{env.NEW_RELIC_ACCOUNT_ID}}

      - name: Destroy Terraform
        run: |
          terraform destroy -auto-approve -var=${{env.NEW_RELIC_API_KEY}} -var=${{env.NEW_RELIC_ACCOUNT_ID}}
